# Comments above each hook indicate the existing hook whose behaviour they mirror

# https://github.com/pre-commit/mirrors-mypy/blob/main/.pre-commit-hooks.yaml
- id: mypy
  name: mypy
  description: ''
  entry: uv run mypy
  language: system
  types_or: [python, pyi]
  args: ["--ignore-missing-imports", "--scripts-are-modules"]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: 2.9.2
- id: mypy-all-files
  name: mypy (all files)
  description: ''
  entry: uv-run-on-all-files
  args: [mypy, python, pyi]
  language: python
  language_version: python3
  types_or: [python, pyi]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: 2.9.2
# https://github.com/RobertCraigie/pyright-python/blob/main/.pre-commit-hooks.yaml
- id: pyright
  name: pyright
  description: 'Python command line wrapper for pyright, a static type checker'
  entry: uv run pyright
  language: system
  types_or: [python, pyi]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: 2.9.2
- id: pyright-all-files
  name: pyright (all files)
  description: 'Python command line wrapper for pyright, a static type checker (all files)'
  entry: uv-run-on-all-files
  args: [pyright, python, pyi]
  language: python
  language_version: python3
  types_or: [python, pyi]
  require_serial: true
  minimum_pre_commit_version: 2.9.2
  additional_dependencies: []
