repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.10
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/wlritchi/pre-commit-via-uv
    rev: 1.0.0
    hooks:
      - id: pyright-all-files
